name: Validate JSON

on:
  push:
    paths:
      - '**/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      - name: Validate JSON files
        run: |
          for file in $(find . -name "*.json"); do
            echo "Validating $file"
            jq . "$file" > /dev/null
          done
